### ISSUE TITLE
`actions-rs/cargo` is deprecated

### ISSUE THREAD

**Issue by niooss-ledger** [LedgerHQ/ledger-app-workflows#83]
Hello,

This project is using https://github.com/actions-rs/cargo:
https://github.com/LedgerHQ/ledger-app-workflows/blob/a4be1a06435ab695f0f02be10b7983c58554e3f8/.github/workflows/reusable_lint.yml#L49-L54

However this action has been archived on Oct 13, 2023 and should be replaced by something else. As the container image which is used (`ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest`) already includes `cargo`, I believe this could be replaced with:

```yaml
  - name: Lint check for Rust app 
    if: ${{ needs.call_get_app_metadata.outputs.is_rust == 'true'}}
    run: cargo fmt --all -- --check 
```

What do you think?
